#!/bin/bash
# Quick Reference Script for DP832 Battery Simulator
# This script shows common usage examples

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║        DP832 Battery Simulator - Quick Reference              ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "Available Examples:"
echo ""
echo "1. Single Channel (LiFePO4)"
echo "   dp832_battery_sim -p profiles/lifepo4.json"
echo ""
echo "2. Two Channels (LiFePO4 + Li-ion)"
echo "   dp832_battery_sim \\"
echo "     -p profiles/lifepo4.json \\"
echo "     -p profiles/liion_18650.json"
echo ""
echo "3. Three Channels (All chemistries)"
echo "   dp832_battery_sim \\"
echo "     -p profiles/lifepo4.json \\"
echo "     -p profiles/liion_18650.json \\"
echo "     -p profiles/lipo_1s.json"
echo ""
echo "4. With Configuration File"
echo "   dp832_battery_sim --config examples/single_channel.toml"
echo ""
echo "5. Chemistry Comparison"
echo "   dp832_battery_sim \\"
echo "     -p profiles/lifepo4.json \\"
echo "     -p profiles/liion_18650.json \\"
echo "     --log logs/comparison.csv"
echo ""
echo "6. NiMH vs Lead-Acid"
echo "   dp832_battery_sim \\"
echo "     -p profiles/nimh_aa.json \\"
echo "     -p profiles/lead_acid_6v.json"
echo ""
echo "7. High-Power Testing (LiPo + LiFePO4 3S)"
echo "   dp832_battery_sim \\"
echo "     -p profiles/lipo_1s.json \\"
echo "     -p profiles/lifepo4_3s.json"
echo ""
echo "Available Profiles:"
echo "  - profiles/lifepo4.json       (LiFePO4 1S, 3.2Ah, CH1)"
echo "  - profiles/lifepo4_3s.json    (LiFePO4 3S, 10Ah, CH3)"
echo "  - profiles/liion_18650.json   (Li-ion 18650, 2.5Ah, CH2)"
echo "  - profiles/lipo_1s.json       (LiPo 1S, 1.2Ah, CH3)"
echo "  - profiles/nimh_aa.json       (NiMH AA, 2.0Ah, CH1)"
echo "  - profiles/lead_acid_6v.json  (Lead-Acid 6V, 4.5Ah, CH2)"
echo ""
echo "Configuration Files:"
echo "  - examples/single_channel.toml"
echo "  - examples/three_channels.toml"
echo "  - examples/chemistry_comparison.toml"
echo "  - examples/development.toml"
echo ""
echo "Keyboard Controls:"
echo "  q - Quit simulator"
echo "  r - Reset SoC to 100% on all channels"
echo ""
echo "For more information, see:"
echo "  - profiles/README.md"
echo "  - examples/README.md"
echo ""
